fix: Correct the format for start-args
The input args is expecting split key value pair, instead of whole
'<key> <value>' format, hence we should split start-args accordingly.

Without this change, we will face the below example error:

```
/usr/bin/chmod +x /home/runner/work/_temp/9526b1b6-7755-4e7d-abee-6ab1a86fd52e
/home/runner/bin/minikube version --short
v1.28.0
/home/runner/bin/minikube start --cni false --network-plugin cni --wait false --nodes 3
Error: unknown flag: --nodes 3
```

Signed-off-by: Tam Mach <sayboras@yahoo.com>